apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      cluster-role: primary
      cloud: azure
    includeSelectors: false
    includeTemplates: true

patches:
  - path: serviceaccount-patch.yaml
