apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  cluster-role: failover
  cloud: gcp

patches:
  - path: ingress-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: deployment-patch.yaml
