# GCP Workload Identity annotation
# Maps the K8s ServiceAccount to a GCP Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    iam.gke.io/gcp-service-account: "api@GCP_PROJECT_ID.iam.gserviceaccount.com"
