# OCI Workload Identity annotation
# The value is patched by ArgoCD ApplicationSet with the actual dynamic group
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    oci.oraclecloud.com/workload-identity: "enabled"
